"""baseline: full schema as of Plan 2 (pre-tenancy)

Revision ID: 0001
Revises: 
Create Date: 2026-07-08 09:16:19.269128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('managers',
    sa.Column('manager_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('manager_id')
    )
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managers_manager_id'), ['manager_id'], unique=False)

    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_expires_at'), ['expires_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('deals',
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('vintage', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.manager_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('deal_id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_manager_id'), ['manager_id'], unique=False)

    op.create_table('deal_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_access_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_access_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('full_text_md', sa.Text(), nullable=True),
    sa.Column('parse_tier', sa.Integer(), nullable=True),
    sa.Column('doc_category', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_doc_category'), ['doc_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_scope'), ['scope'], unique=False)

    op.create_table('ingest_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('child_total', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('doc_id', sa.String(), nullable=True),
    sa.Column('doc_category', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_jobs_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_jobs_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_jobs_status'), ['status'], unique=False)

    op.create_table('positions',
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('commitment_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('called_amount', sa.Float(), nullable=True),
    sa.Column('distributed_amount', sa.Float(), nullable=True),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('as_of', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('row_source', sa.String(), nullable=True),
    sa.Column('output_format', sa.String(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('cloned_from', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cloned_from'], ['workflows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_is_builtin'), ['is_builtin'], unique=False)

    op.create_table('workflow_columns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('is_derived', sa.Boolean(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_columns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_columns_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('document_ids_json', sa.Text(), nullable=True),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_stages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('prompt_md', sa.Text(), nullable=True),
    sa.Column('checkpoint', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_stages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_stages_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_variables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_variables_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_variables_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('assistant_stage_outputs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('prompt_md', sa.Text(), nullable=True),
    sa.Column('checkpoint', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('output_md', sa.Text(), nullable=True),
    sa.Column('edited_md', sa.Text(), nullable=True),
    sa.Column('citations_json', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('fallback', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_stage_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_stage_outputs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_stage_outputs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_stage_outputs_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_stage_outputs_status'), ['status'], unique=False)

    op.create_table('tabular_cells',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('row_key', sa.String(), nullable=False),
    sa.Column('column_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answer_formatted_json', sa.Text(), nullable=True),
    sa.Column('citations_json', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('fallback', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['workflow_columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tabular_cells', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tabular_cells_column_id'), ['column_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tabular_cells_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tabular_cells_row_key'), ['row_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_tabular_cells_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tabular_cells_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabular_cells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tabular_cells_status'))
        batch_op.drop_index(batch_op.f('ix_tabular_cells_run_id'))
        batch_op.drop_index(batch_op.f('ix_tabular_cells_row_key'))
        batch_op.drop_index(batch_op.f('ix_tabular_cells_id'))
        batch_op.drop_index(batch_op.f('ix_tabular_cells_column_id'))

    op.drop_table('tabular_cells')
    with op.batch_alter_table('assistant_stage_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_stage_outputs_status'))
        batch_op.drop_index(batch_op.f('ix_assistant_stage_outputs_stage_id'))
        batch_op.drop_index(batch_op.f('ix_assistant_stage_outputs_run_id'))
        batch_op.drop_index(batch_op.f('ix_assistant_stage_outputs_id'))

    op.drop_table('assistant_stage_outputs')
    with op.batch_alter_table('workflow_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_variables_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_variables_id'))

    op.drop_table('workflow_variables')
    with op.batch_alter_table('workflow_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_stages_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_stages_id'))

    op.drop_table('workflow_stages')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_deal_id'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('workflow_columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_columns_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_columns_id'))

    op.drop_table('workflow_columns')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_is_builtin'))
        batch_op.drop_index(batch_op.f('ix_workflows_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_deal_id'))

    op.drop_table('workflows')
    op.drop_table('positions')
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_parent_id'))
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_deal_id'))

    op.drop_table('ingest_jobs')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_scope'))
        batch_op.drop_index(batch_op.f('ix_documents_doc_id'))
        batch_op.drop_index(batch_op.f('ix_documents_doc_category'))

    op.drop_table('documents')
    with op.batch_alter_table('deal_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_deal_access_deal_id'))

    op.drop_table('deal_access')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_manager_id'))
        batch_op.drop_index(batch_op.f('ix_deals_entity_type'))
        batch_op.drop_index(batch_op.f('ix_deals_deal_id'))

    op.drop_table('deals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_expires_at'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managers_manager_id'))

    op.drop_table('managers')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_deal_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
